### PR TITLE
Name switch fix

### PR DESCRIPTION
**Pull request by arvindraghavan**
Only the 04 file is changed, the rest are untouched in the output.

### CODE REVIEW

**Comment by kdawgsf** [comment]
Is this replaced by #25 , i.e. can it be closed?

**Comment by arvindraghavan** [comment]
@kdawgsf, I created two separate PRs (and two branches) so that we can use this PR/branch to first get the name-switch right. You've already identified a couple of issues (I knew I could count on you...) and I think it may be a good idea to fix those issues in this branch first. The informal_sal can then be rebased on top of this one as a separate step once this name-fix "feature" is done. What do you think?

**Comment by arvindraghavan** [comment]
@kdawgsf, I added a simple fix to switch mobile and e-mails too.

**Comment by kdawgsf** [comment]
I rebased the change to get rid of the already-merged commit. This is the second time I've looked at this change, and I have to admit I don't understand how it works. I would have expected a conditional to be required on whether to do the name switch. What am I missing?

**Comment by kdawgsf** [comment]
@arvindraghavan ping

**Comment by arvindraghavan** [comment]
@kdawgsf, sorry, I missed/misunderstood the question. I used a conditional only in the code where I try to update the informal_sal, because in that situation, I explicitly don't want an update to occur if the switched names don't match what DP would have if its data was auto-generated from a previous upload. In all other cases, I am simply assuming that the District data is the reference, so I've written to script to *try to update* all these additional fields for a donor. Of course DP import is smart, so it will update only if there is a change. I'm basically leaving the conditional for DP to enforce.

**Comment by arvindraghavan** [comment]
@kdawgsf, I assume you are still in some significantly eastward time zone. I plan to make the changes required to fix the un-updated fields (salutation, optional line). I expect these to be straightforward, but I think it now makes sense to have only one PR. So please hold off on these PRs for a bit till give you the go-ahead.

**Pull request closed without merging**
